### ISSUE TITLE
Cross-process communication

### ISSUE THREAD

**Issue by asbjornu** [didil/goblero#13]
Currently, it seems that Goblero requires the same, single instance of `blero.Blero` to receive calls to `EnqueueJob` in order for `RegisterProcessorFunc` to be invoked. This makes cross-process communication, for instance between two different HTTP servers trying to communicate with each other, impossible.

Since Goblero is synchronizing state to disk with BadgerDB, it should be possible to enable communication across processes, no? If this is already possible, I would love to know how, because I'm unable to get it to work.

**Comment by didil** [comment]
@asbjornu can you please explain the use case ? I'm not sure about what you're trying to achieve

**Comment by asbjornu** [comment]
@didil, thank you for the swift reply!

I have a project where I spin up two different instances of [Gin](https://github.com/gin-gonic/gin). I would like to be able to enqueue jobs from these two HTTP servers (let's call them Server A and Server B), while having a third worker process the enqueued jobs. Currently it seems like Goblero can only process jobs enqueued on the same instance of the `blero.Blero`, within the same OS process.

So I could spin up Goblero processing inside Server A and enqueue jobs in Server A, but if I enqueue jobs in Server B, the Goblero processor within Server A won't see them.

**Comment by didil** [comment]
@asbjornu ok thanks for explaining. So goblero only aims to solve the in-process job queue part. The implementer is free to choose how jobs are created by your process. For example you could receive them via an http server or by consuming from a redis queue then enqueing them to the Blero instance .

**Comment by asbjornu** [comment]
I see. Thank you for the rationale and explanation.
